//! Generated from minecraft-data `pc/1.20` entities.json — do not edit.
//! All living mob types with gameplay stats for the AI/spawner.

pub struct MobRow {
    pub name: &'static str,
    pub type_id: i32,
    pub hostile: bool,
    pub max_health: f32,
    pub speed: f64,
    pub attack: f32,
}

/// All 80 living mob types.
pub static MOBS: &[MobRow] = &[
    MobRow { name: "allay", type_id: 0, hostile: false, max_health: 10.0, speed: 0.13, attack: 0.0 },
    MobRow { name: "armor_stand", type_id: 2, hostile: false, max_health: 10.0, speed: 0.13, attack: 0.0 },
    MobRow { name: "axolotl", type_id: 4, hostile: false, max_health: 10.0, speed: 0.13, attack: 0.0 },
    MobRow { name: "bat", type_id: 5, hostile: false, max_health: 10.0, speed: 0.13, attack: 0.0 },
    MobRow { name: "bee", type_id: 6, hostile: false, max_health: 10.0, speed: 0.2, attack: 2.0 },
    MobRow { name: "blaze", type_id: 7, hostile: true, max_health: 20.0, speed: 0.18, attack: 5.0 },
    MobRow { name: "camel", type_id: 10, hostile: false, max_health: 10.0, speed: 0.13, attack: 0.0 },
    MobRow { name: "cat", type_id: 11, hostile: false, max_health: 10.0, speed: 0.15, attack: 0.0 },
    MobRow { name: "cave_spider", type_id: 12, hostile: true, max_health: 12.0, speed: 0.24, attack: 2.0 },
    MobRow { name: "chicken", type_id: 15, hostile: false, max_health: 4.0, speed: 0.12, attack: 0.0 },
    MobRow { name: "cod", type_id: 16, hostile: false, max_health: 10.0, speed: 0.13, attack: 0.0 },
    MobRow { name: "cow", type_id: 18, hostile: false, max_health: 10.0, speed: 0.13, attack: 0.0 },
    MobRow { name: "creeper", type_id: 19, hostile: true, max_health: 20.0, speed: 0.14, attack: 6.0 },
    MobRow { name: "dolphin", type_id: 20, hostile: false, max_health: 10.0, speed: 0.13, attack: 0.0 },
    MobRow { name: "donkey", type_id: 21, hostile: false, max_health: 10.0, speed: 0.13, attack: 0.0 },
    MobRow { name: "drowned", type_id: 23, hostile: true, max_health: 20.0, speed: 0.16, attack: 2.0 },
    MobRow { name: "elder_guardian", type_id: 25, hostile: true, max_health: 20.0, speed: 0.16, attack: 2.0 },
    MobRow { name: "ender_dragon", type_id: 27, hostile: true, max_health: 20.0, speed: 0.16, attack: 2.0 },
    MobRow { name: "enderman", type_id: 29, hostile: true, max_health: 40.0, speed: 0.25, attack: 7.0 },
    MobRow { name: "endermite", type_id: 30, hostile: true, max_health: 20.0, speed: 0.16, attack: 2.0 },
    MobRow { name: "evoker", type_id: 31, hostile: true, max_health: 20.0, speed: 0.16, attack: 2.0 },
    MobRow { name: "fox", type_id: 38, hostile: false, max_health: 10.0, speed: 0.18, attack: 2.0 },
    MobRow { name: "frog", type_id: 39, hostile: false, max_health: 10.0, speed: 0.13, attack: 0.0 },
    MobRow { name: "ghast", type_id: 41, hostile: true, max_health: 20.0, speed: 0.16, attack: 2.0 },
    MobRow { name: "giant", type_id: 42, hostile: true, max_health: 20.0, speed: 0.16, attack: 2.0 },
    MobRow { name: "glow_squid", type_id: 44, hostile: false, max_health: 10.0, speed: 0.13, attack: 0.0 },
    MobRow { name: "goat", type_id: 45, hostile: false, max_health: 10.0, speed: 0.13, attack: 0.0 },
    MobRow { name: "guardian", type_id: 46, hostile: true, max_health: 20.0, speed: 0.16, attack: 2.0 },
    MobRow { name: "hoglin", type_id: 47, hostile: true, max_health: 20.0, speed: 0.16, attack: 2.0 },
    MobRow { name: "horse", type_id: 49, hostile: false, max_health: 15.0, speed: 0.2, attack: 0.0 },
    MobRow { name: "husk", type_id: 50, hostile: true, max_health: 20.0, speed: 0.16, attack: 3.0 },
    MobRow { name: "illusioner", type_id: 51, hostile: true, max_health: 20.0, speed: 0.16, attack: 2.0 },
    MobRow { name: "iron_golem", type_id: 53, hostile: false, max_health: 100.0, speed: 0.13, attack: 15.0 },
    MobRow { name: "llama", type_id: 60, hostile: false, max_health: 10.0, speed: 0.13, attack: 0.0 },
    MobRow { name: "magma_cube", type_id: 62, hostile: true, max_health: 20.0, speed: 0.16, attack: 2.0 },
    MobRow { name: "mooshroom", type_id: 65, hostile: false, max_health: 10.0, speed: 0.13, attack: 0.0 },
    MobRow { name: "mule", type_id: 66, hostile: false, max_health: 10.0, speed: 0.13, attack: 0.0 },
    MobRow { name: "ocelot", type_id: 67, hostile: false, max_health: 10.0, speed: 0.18, attack: 0.0 },
    MobRow { name: "panda", type_id: 69, hostile: false, max_health: 20.0, speed: 0.13, attack: 4.0 },
    MobRow { name: "parrot", type_id: 70, hostile: false, max_health: 10.0, speed: 0.13, attack: 0.0 },
    MobRow { name: "phantom", type_id: 71, hostile: true, max_health: 20.0, speed: 0.16, attack: 2.0 },
    MobRow { name: "pig", type_id: 72, hostile: false, max_health: 10.0, speed: 0.13, attack: 0.0 },
    MobRow { name: "piglin", type_id: 73, hostile: true, max_health: 20.0, speed: 0.16, attack: 2.0 },
    MobRow { name: "piglin_brute", type_id: 74, hostile: true, max_health: 20.0, speed: 0.16, attack: 2.0 },
    MobRow { name: "pillager", type_id: 75, hostile: true, max_health: 20.0, speed: 0.16, attack: 2.0 },
    MobRow { name: "polar_bear", type_id: 76, hostile: false, max_health: 10.0, speed: 0.13, attack: 0.0 },
    MobRow { name: "pufferfish", type_id: 78, hostile: false, max_health: 10.0, speed: 0.13, attack: 0.0 },
    MobRow { name: "rabbit", type_id: 79, hostile: false, max_health: 3.0, speed: 0.2, attack: 0.0 },
    MobRow { name: "ravager", type_id: 80, hostile: true, max_health: 20.0, speed: 0.16, attack: 2.0 },
    MobRow { name: "salmon", type_id: 81, hostile: false, max_health: 10.0, speed: 0.13, attack: 0.0 },
    MobRow { name: "sheep", type_id: 82, hostile: false, max_health: 8.0, speed: 0.13, attack: 0.0 },
    MobRow { name: "shulker", type_id: 83, hostile: true, max_health: 20.0, speed: 0.16, attack: 2.0 },
    MobRow { name: "silverfish", type_id: 85, hostile: true, max_health: 20.0, speed: 0.16, attack: 2.0 },
    MobRow { name: "skeleton", type_id: 86, hostile: true, max_health: 20.0, speed: 0.16, attack: 2.0 },
    MobRow { name: "skeleton_horse", type_id: 87, hostile: true, max_health: 20.0, speed: 0.16, attack: 2.0 },
    MobRow { name: "slime", type_id: 88, hostile: true, max_health: 16.0, speed: 0.15, attack: 2.0 },
    MobRow { name: "sniffer", type_id: 90, hostile: false, max_health: 10.0, speed: 0.13, attack: 0.0 },
    MobRow { name: "snow_golem", type_id: 91, hostile: false, max_health: 10.0, speed: 0.13, attack: 0.0 },
    MobRow { name: "spider", type_id: 95, hostile: true, max_health: 16.0, speed: 0.22, attack: 2.0 },
    MobRow { name: "squid", type_id: 96, hostile: false, max_health: 10.0, speed: 0.13, attack: 0.0 },
    MobRow { name: "stray", type_id: 97, hostile: true, max_health: 20.0, speed: 0.16, attack: 2.0 },
    MobRow { name: "strider", type_id: 98, hostile: false, max_health: 10.0, speed: 0.13, attack: 0.0 },
    MobRow { name: "tadpole", type_id: 99, hostile: false, max_health: 10.0, speed: 0.13, attack: 0.0 },
    MobRow { name: "trader_llama", type_id: 103, hostile: false, max_health: 10.0, speed: 0.13, attack: 0.0 },
    MobRow { name: "tropical_fish", type_id: 105, hostile: false, max_health: 10.0, speed: 0.13, attack: 0.0 },
    MobRow { name: "turtle", type_id: 106, hostile: false, max_health: 10.0, speed: 0.13, attack: 0.0 },
    MobRow { name: "vex", type_id: 107, hostile: true, max_health: 20.0, speed: 0.16, attack: 2.0 },
    MobRow { name: "villager", type_id: 108, hostile: false, max_health: 20.0, speed: 0.12, attack: 0.0 },
    MobRow { name: "vindicator", type_id: 109, hostile: true, max_health: 20.0, speed: 0.16, attack: 2.0 },
    MobRow { name: "wandering_trader", type_id: 110, hostile: false, max_health: 10.0, speed: 0.13, attack: 0.0 },
    MobRow { name: "warden", type_id: 111, hostile: true, max_health: 20.0, speed: 0.16, attack: 2.0 },
    MobRow { name: "witch", type_id: 112, hostile: true, max_health: 26.0, speed: 0.16, attack: 0.0 },
    MobRow { name: "wither", type_id: 113, hostile: true, max_health: 20.0, speed: 0.16, attack: 2.0 },
    MobRow { name: "wither_skeleton", type_id: 114, hostile: true, max_health: 20.0, speed: 0.16, attack: 2.0 },
    MobRow { name: "wolf", type_id: 116, hostile: false, max_health: 8.0, speed: 0.18, attack: 4.0 },
    MobRow { name: "zoglin", type_id: 117, hostile: true, max_health: 20.0, speed: 0.16, attack: 2.0 },
    MobRow { name: "zombie", type_id: 118, hostile: true, max_health: 20.0, speed: 0.16, attack: 3.0 },
    MobRow { name: "zombie_horse", type_id: 119, hostile: true, max_health: 20.0, speed: 0.16, attack: 2.0 },
    MobRow { name: "zombie_villager", type_id: 120, hostile: true, max_health: 20.0, speed: 0.16, attack: 2.0 },
    MobRow { name: "zombified_piglin", type_id: 121, hostile: true, max_health: 20.0, speed: 0.18, attack: 5.0 },
];
